language: python
python:
    - "2.7"

before_install:
    - sudo apt-get purge elasticsearch -fy
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb
    - sudo dpkg -i elasticsearch-1.2.1.deb
    - sudo service elasticsearch restart
    - sleep 10  # Let it breathe! :D

install:
    - /usr/share/elasticsearch/bin/elasticsearch -v

before_script:
    - curl http://localhost:9200/  # Check if ES is up and listening

script:
    - python setup.py install
    - ./run test
