language: python
python:
    - 2.7
    - 3.4
    - pypy

install:
    - make setup
    - python setup.py install

script:
    # ES 0.9 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.13.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-0.90.13.deb
    - sudo service elasticsearch restart
    - sleep 10  # Wait for ElasticSearch
    - curl http://localhost:9200/  # Check if ES is up and listening
    - make bulk  # Create indices and add some documents
    - make test
    - sudo service elasticsearch stop

    # ES 1.0 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.3.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.0.3.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.1 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.2.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.1.2.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.2 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.2.4.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.3 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.9.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.3.9.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.4 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.5.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.4.5.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.5 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.2.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.5.2.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.6 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.6.2.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.6.2.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.7 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-1.7.1.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop

    # ES 2.0 branch
    - wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.0.0-beta1/elasticsearch-2.0.0-beta1.deb
    - sudo apt-get purge elasticsearch -fy
    - sudo dpkg -i --force-confnew elasticsearch-2.0.0-beta1.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - make bulk
    - make test
    - sudo service elasticsearch stop
