language: python
python:
    - 2.7
    - 3.4
    - pypy

before_install:
    - sudo apt-get purge elasticsearch -fy

install:
    - make setup
    - python setup.py install

script:
    # ES 1.0 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.3.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.0.3.deb
    - sudo service elasticsearch start
    - sleep 10  # Let it breathe! :D
    - curl http://localhost:9200/  # Check if ES is up and listening
    - ./run bulk  # Create indices and add some docs
    - make test
    - sudo service elasticsearch stop

    # ES 1.1 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.2.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.1.2.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - ./run bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.2 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.2.4.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - ./run bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.3 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.7.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.3.7.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - ./run bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.4 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.4.4.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - ./run bulk
    - make test
    - sudo service elasticsearch stop

    # ES 1.5 branch
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.5.0.deb
    - sudo dpkg -i --force-confnew elasticsearch-1.5.0.deb
    - sudo service elasticsearch start
    - sleep 10
    - curl http://localhost:9200/
    - ./run bulk
    - make test
    - sudo service elasticsearch stop
